### ISSUE TITLE
Update General Concepts page to state parallel IO is possible with threads

### ISSUE THREAD

**Issue by ghost** [calvinchengx/learngeventsocketio#2]
http://learn-gevent-socketio.readthedocs.io/en/latest/general_concepts.html#so-we-cannot-execute-in-parallel-with-python

In the above linked page, it says that parallel IO is not possible using the threading module.

This is incorrect. All IO operations are handled by the kernel and release the GIL, so parallel IO is possible.

References: Page 35 of http://www.dabeaz.com/python/UnderstandingGIL.pdf

I ran my own not very scientific tests to verify. Here is the code https://github.com/ploggingdev/python_learn/blob/master/multithread_demo/file_copy.py

To use 2 threads update line 30.

**Comment by calvinchengx** [comment]
Looks like you are right! Thanks for pointing out my error. Appreciate it.

---

www.calvinx.com

On Tue, 10 Jan 2017 at 4:23 PM ploggingdev

<
mailto:ploggingdev <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

http://learn-gevent-socketio.readthedocs.io/en/latest/general_concepts.html#so-we-cannot-execute-in-parallel-with-python

In the above linked page, it says that parallel IO is not possible using the threading module.

This is incorrect. All IO operations are handled by the kernel and release the GIL, so parallel IO is possible.

References: Page 35 of
http://www.dabeaz.com/python/UnderstandingGIL.pdf

I ran my own not very scientific tests to verify. Here is the code
https://github.com/ploggingdev/python_learn/blob/master/multithread_demo/file_copy.py

To use 2 threads update line 30.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/calvinchengx/learngeventsocketio/issues/2
, or
